name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repotisory
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |-
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            libglfw3 \
            libglfw3-dev \
            libglew-dev \
            libsdl2-dev \
            libsdl2-ttf-dev
      - name: Build Demo (opengl2)
        run: make -C demo/glfw_opengl2
      - name: Build Demo (opengl3)
        run: make -C demo/glfw_opengl3
      - name: Build SDL2_gfx
        run: |-
          cd dependencies/SDL2_gfx-1.0.4
          ./configure
          make
          sudo make install
      - name: Build Demo (SDL)
        run: make -C demo/sdl_native
      - name: Build Example
        run: make -C example
      - name: Generate nuklear.h
        run: cd src && ./paq.sh > ../nuklear.h
